// <auto-generated />
using System;
using ApiGroupProject.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGroupProject.Migrations
{
    [DbContext(typeof(WarriorContext))]
    [Migration("20230512145930_initializ")]
    partial class initializ
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Library.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeName = "Damir",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeName = "Daniel",
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeName = "Filip",
                            ProjectId = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            EmployeeName = "Anas",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 5,
                            EmployeeName = "Alvin",
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("Library.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ProjectName = "Group1"
                        },
                        new
                        {
                            ProjectId = 2,
                            ProjectName = "Group2"
                        },
                        new
                        {
                            ProjectId = 3,
                            ProjectName = "Group3"
                        });
                });

            modelBuilder.Entity("Library.TimeReport", b =>
                {
                    b.Property<int>("TimeReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeReportId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("TimeReportId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeReports");

                    b.HasData(
                        new
                        {
                            TimeReportId = 1,
                            EmployeeId = 2,
                            Hours = 8,
                            Week = 15
                        },
                        new
                        {
                            TimeReportId = 2,
                            EmployeeId = 2,
                            Hours = 20,
                            Week = 10
                        },
                        new
                        {
                            TimeReportId = 3,
                            EmployeeId = 3,
                            Hours = 40,
                            Week = 40
                        },
                        new
                        {
                            TimeReportId = 4,
                            EmployeeId = 5,
                            Hours = 32,
                            Week = 18
                        },
                        new
                        {
                            TimeReportId = 5,
                            EmployeeId = 4,
                            Hours = 37,
                            Week = 36
                        },
                        new
                        {
                            TimeReportId = 6,
                            EmployeeId = 4,
                            Hours = 40,
                            Week = 14
                        });
                });

            modelBuilder.Entity("Library.Employee", b =>
                {
                    b.HasOne("Library.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Library.TimeReport", b =>
                {
                    b.HasOne("Library.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
